#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "gruvbox"
    # colorscheme = "SpaceVim"
    colorscheme = "default"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    filemanager = "defx"

    disabled_plugins = ["deoplete.nvim", "asyncomplete.vim"]

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#c'
cpp = 'c11'
# enable_clang_syntax_highlight = true

[[layers]]
name = 'lsp'
filetypes = [
  'c',
  'cpp'
]
[layers.override_cmd]
c = ['clangd']

[[layers]]
name = "lang#rust"

[[layers]]
name = "lsp"
filetypes = [
  "rust"
]
[layers.override_cmd]
rust = ["rls"]

[[layers]]
name = "format"

[[layers]]
name = 'colorscheme'

[[custom_plugins]]
name = "mhartington/oceanic-next"
merged = false

[[custom_plugins]]
name = "rafi/awesome-vim-colorschemes"
merged = false

[[custom_plugins]]
name = "neoclide/coc.nvim"
merged = false

[[custom_plugins]]
name = "jiangmiao/auto-pairs"
merged = false
