#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "xcodelight"
    colorscheme_bg = "light"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    autocomplete_method = "coc"

    # filemanager = "defx"

    disabled_plugins = ["fcitx.vim", "neomake"]

    enable_vimfiler_welcome = false
    # enable_cursorcolumn = true
    # enable_cursorline = true
    project_rooter_outermost = false

    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"
auto_completion_enable_snippets_in_popup = false
auto_completion_delay = 200
auto_completion_complete_with_key_sequence = "nil"
auto_completion_complete_with_key_sequence_delay = 0.1

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'fzf'
# name = 'leaderf'

[[layers]]
name = 'git'
git_plugin = 'fugitive'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'format'

[[layers]]
name = 'lsp'
filetypes = [
  'c',
  'cpp',
  'python',
  # 'rust',
  # 'julia',
]
[layers.override_cmd]
  # rust = ["rust-analyzer"]
  # rust = ["rls"]

[[layers]]
name = 'lang#c'
# enable_clang_syntax_highlight = true

# [[layers]]
# name = "lang#rust"
#
# [[layers]]
# name = "lang#julia"

[[layers]]
name = "lang#python"
enable_typeinfo = true
python_file_head = [
    '#!/usr/bin/env python',
    '# -*- coding: utf-8 -*-',
    '',
    ''
]

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#vim"

[[layers]]
name = 'colorscheme'
# random_theme = true
# frequency = "hourly" #daily, hourly, weekly

[[custom_plugins]]
name = 'roxma/nvim-yarp'
merged = false

[[custom_plugins]]
name = 'roxma/vim-hug-neovim-rpc'
merged = false

# [[custom_plugins]]
# name = 'jackguo380/vim-lsp-cxx-highlight'
# merged = false
#

# [[custom_plugins]]
# # name = "rafi/awesome-vim-colorschemes"
# # name = 'flazz/vim-colorschemes'
# name = 'mswift42/vim-themes'

[[custom_plugins]]
name = 'rhysd/vim-color-spring-night'
merged = false
[[custom_plugins]]
name = 'mhinz/vim-janah'
merged = false
[[custom_plugins]]
name = 'mhartington/oceanic-next'
merged = false
[[custom_plugins]]
name = 'hzchirs/vim-material'
merged = false
[[custom_plugins]]
name = 'joshdick/onedark.vim'
merged = false
[[custom_plugins]]
name = 'drewtempelmeyer/palenight.vim'
merged = false
[[custom_plugins]]
name = 'altercation/vim-colors-solarized'
merged = false
[[custom_plugins]]
name = 'ajmwagar/vim-deus'
merged = false
[[custom_plugins]]
name = 'romgrk/doom-one.vim'
merged = false
[[custom_plugins]]
name = 'sjl/badwolf'
merged = false
[[custom_plugins]]
name = 'jacoborus/tender.vim'
merged = false
[[custom_plugins]]
name = 'nanotech/jellybeans.vim'
merged = false
# [[custom_plugins]]
# name = 'phongnh/vim-leaderf-solarized-theme'
# merged = false
[[custom_plugins]]
name = 'itchyny/landscape.vim'
merged = false
[[custom_plugins]]
name = 'rakr/vim-one'
merged = false
[[custom_plugins]]
name = 'arcticicestudio/nord-vim'
merged = false
[[custom_plugins]]
name = 'srcery-colors/srcery-vim'
merged = false
[[custom_plugins]]
name = 'connorholyday/vim-snazzy'
merged = false
[[custom_plugins]]
name = 'jnurmine/Zenburn'
merged = false
[[custom_plugins]]
name = 'dracula/vim'
merged = false
[[custom_plugins]]
name = 'tomasiser/vim-code-dark'
merged = false
[[custom_plugins]]
name = 'mg979/vim-studio-dark'
merged = false
[[custom_plugins]]
name = 'arzg/vim-colors-xcode'
merged = false
[[custom_plugins]]
name = 'wojciechkepka/vim-github-dark'
merged = false
