#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    disabled_plugins = ["neomake"]
    enable_language_specific_leader = false


# # add these in .SpaceVim/config/main.vim
# set nocompatible
# let &t_TI = ""
# let &t_TE = ""
# let g:mapleader = ','


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'float'
default_height = 50

[[layers]]
  name = 'lang#c'
  enable_clang_syntax_highlight = true
[[layers]]
  name = "lsp"
  filetypes = [
    "c",
    "cpp"
  ]
  [layers.override_cmd]
    c = ["clangd"]

[[layers]]
  name = "git"

[[layers]]
  # name = "fzf"
  name = "leaderf"

[[layers]]
  name = "colorscheme"

[[custom_plugins]]
name = "rafi/awesome-vim-colorschemes"
merged = false

[[custom_plugins]]
name = 'tomasiser/vim-code-dark'
merged = false

[[custom_plugins]]
name = 'mg979/vim-studio-dark'
merged = false

[[layers]]
  name = "colorscheme"
  random_theme = false
  frequency = "daily"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#python"
  enable_typeinfo = true
  python_file_head = [
      '#!/usr/bin/env python',
      '# -*- coding: utf-8 -*-',
      '',
      ''
  ]

[[custom_plugins]]
name = 'jackguo380/vim-lsp-cxx-highlight'
merged = false

[[custom_plugins]]
name = 'jiangmiao/auto-pairs'
merged = false
